apiVersion: v1
kind: Service
metadata:
  name: chroma
  namespace: {{ include "resto-rag.namespace" . }}
  labels:
    app.kubernetes.io/component: chroma
    {{- include "resto-rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chroma.service.type }}
  selector:
    app.kubernetes.io/component: chroma
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.chroma.service.port }}
      targetPort: 8000
