apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ include "resto-rag.namespace" . }}
  labels:
    app.kubernetes.io/component: ollama
    {{- include "resto-rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app.kubernetes.io/component: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.ollama.service.port }}
      targetPort: 11434
