apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {{ include "resto-rag.namespace" . }}
  labels:
    app.kubernetes.io/component: qdrant
    {{- include "resto-rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qdrant.service.type }}
  selector:
    app.kubernetes.io/component: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.qdrant.service.port }}
      targetPort: 6333
