apiVersion: v1
kind: Service
metadata:
  name: resto
  namespace: {{ include "resto-rag.namespace" . }}
  labels:
    app.kubernetes.io/component: resto
    {{- include "resto-rag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.resto.service.type }}
  selector:
    app.kubernetes.io/component: resto
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.resto.service.port }}
      targetPort: 8501
