apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: resto-langfuse
stringData:
  LANGFUSE_SECRET_KEY: sk-lf-c84aee3b-1e53-468e-855b-3845ebe0c6e3
  LANGFUSE_PUBLIC_KEY: pk-lf-f027b44b-7ddf-44ff-aa89-17adf8fd3ea7
  LANGFUSE_BASE_URL: http://langfuse-web.langfuse.svc.cluster.local:3000
