apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: resto-langfuse
stringData:
  LANGFUSE_SECRET_KEY: sk-lf-3fa32de1-6dcc-4f6a-92c9-55c943e9b382
  LANGFUSE_PUBLIC_KEY: pk-lf-e3fa0ab5-1be0-46fe-98c2-f5145f0d28f0
  LANGFUSE_BASE_URL: http://langfuse-web.langfuse.svc.cluster.local:3000
