target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "W", "I"]

[lint.per-file-ignores]
"tests/*.py" = ["E402"]
"winy/app/main.py" = ["E501"]
"winy/tools/create_embeddings.py" = ["E501"]
