images:
  airflow:
    repository: 201714515140.dkr.ecr.eu-central-1.amazonaws.com/airflow-embeddings/production
    tag: latest
    pullPolicy: Always

dags:
  mountPath: /opt/airflow/dags # where Airflow reads DAGs in the pod.
  gitSync:
    enabled: true
    repo: https://github.com/aduku-adp/adp-rags.git
    branch: main
    subPath: dags # folder inside repo containing DAG files.

secret:
  - envName: AWS_ACCESS_KEY_ID
    secretName: airflow-aws-creds
    secretKey: AWS_ACCESS_KEY_ID
  - envName: AWS_SECRET_ACCESS_KEY
    secretName: airflow-aws-creds
    secretKey: AWS_SECRET_ACCESS_KEY
  - envName: AWS_DEFAULT_REGION
    secretName: airflow-aws-creds
    secretKey: AWS_DEFAULT_REGION

env:
  - name: S3_BUCKET
    value: adp-rags
  - name: S3_PREFIX
    value: ""
  - name: QDRANT_HOST
    value: qdrant.adp-rags.svc.cluster.local
  - name: QDRANT_PORT
    value: "6333"
  - name: OLLAMA
    value: http://ollama.adp-rags.svc.cluster.local:11434
