dags:
  mountPath: /opt/airflow/dags # where Airflow reads DAGs in the pod
  gitSync:
    enabled: true
    repo: https://github.com/aduku-adp/adp-rags.git
    branch: main
    subPath: dags # folder inside repo containing DAG files
